version: '2'

services:
  robotdb:
    image: postgres:9.4
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example

  robotbackend:
    build: backend
    command: ./wait-for robotdb:5432 -- npm run dev
    environment:
      DATABASE_URL: postgres://example:example@robotdb/example
    ports:
      - 9000
    depends_on:
      - robotdb

  robotfrontend:
    build: frontend
    environment:
      ENDPOINT: http://robotbackend:9000
    ports:
      - 8000:8000

  robot:
    build: robot
    command: sh -c '/robot/wait-for robotfrontend:8000 -t 10 -r 30 --wget -- python /robot/run.py --exclude failing --outputdir /results'
    environment:
      BROWSER: HeadlessChrome
      SERVER: http://robotfrontend:8000
    volumes:
      - ./robot:/robot:ro
      - ./results/robot:/results:rw
    depends_on:
      - robotfrontend
      - robotbackend
